# Generated by Django 6.0.5 on 2026-05-15 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Router",
            fields=[
                (
                    "hostname",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "ip_administrativa",
                    models.GenericIPAddressField(protocol="IPv4", unique=True),
                ),
                (
                    "ip_loopback",
                    models.GenericIPAddressField(protocol="IPv4", unique=True),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("EDGE", "Edge (Frontera)"),
                            ("CORE", "Core (Núcleo)"),
                            ("LEAF", "Leaf (Hoja/TOR)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("empresa", models.CharField(default="Universidad", max_length=100)),
                (
                    "sistema_operativo",
                    models.CharField(default="Cisco IOS", max_length=100),
                ),
                ("ssh_usuario_admin", models.CharField(default="admin", max_length=50)),
                (
                    "ssh_password_admin",
                    models.CharField(default="admin123", max_length=50),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interfaz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, protocol="IPv4"
                    ),
                ),
                (
                    "netmask",
                    models.GenericIPAddressField(
                        blank=True, null=True, protocol="IPv4"
                    ),
                ),
                ("estado", models.BooleanField(default=True)),
                (
                    "conectado_a",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enlace_reciproco",
                        to="gestion_red.interfaz",
                    ),
                ),
                (
                    "router",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interfaces",
                        to="gestion_red.router",
                    ),
                ),
            ],
            options={
                "unique_together": {("nombre", "router")},
            },
        ),
        migrations.CreateModel(
            name="DispositivoUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("privilegio", models.IntegerField(default=1)),
                (
                    "router",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuarios_red",
                        to="gestion_red.router",
                    ),
                ),
            ],
            options={
                "unique_together": {("username", "router")},
            },
        ),
    ]
