# Generated by Django 5.2.14 on 2026-05-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_red', '0002_alter_dispositivousuario_id_alter_interfaz_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='ssh_password_admin',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
