# Generated by Django 6.0.5 on 2026-05-15 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gestion_red", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitoreoConfig",
            fields=[
                (
                    "interfaz",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="config_monitoreo",
                        serialize=False,
                        to="gestion_red.interfaz",
                    ),
                ),
                ("monitoreo_octetos_activo", models.BooleanField(default=False)),
                ("intervalo_muestreo", models.IntegerField(default=10)),
                ("captura_traps_activa", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="RegistroOcteto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("octetos_entrada", models.BigIntegerField()),
                (
                    "interfaz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="muestras_octetos",
                        to="gestion_red.interfaz",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
